name: CI Saludo

on:
  push:
    branches: ["develop"]
  workflow_dispatch: # Esto permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar saludo
        run: echo "Hola desde GitHub Actions"